### ISSUE TITLE
The directory '/app/staticfiles' in the STATICFILES_DIRS setting does not exist.

### ISSUE THREAD

**Issue by firdavsDev** [bekzod818/Social-Network-Prototype#2]
Run all commands in README.md:
   * collectstatic (262 static files copied.)
   * docker-compose -f docker-compose.dev.yml exec minio mc alias set local http://minio:9000 minioadmin minioadmin
       * mc: Configuration written to `/tmp/.mc/config.json`. Please update your access credentials.
       * mc: Successfully created `/tmp/.mc/share`.
       * mc: Initialized share uploads `/tmp/.mc/share/uploads.json` file.
       * mc: Initialized share downloads `/tmp/.mc/share/downloads.json` file.
       * Added `local` successfully.
   * Access permission for `local/social-network-prototype` is set to `public`

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ce9e39cc-acd9-436d-bb71-3ae016d0a556">

**Comment by bekzod818** [comment]
@firdavsDev o'zgarishlarni pull qilib README.md dagilarni qayta run qilib ishlatib ko'ring. env filega o'zgarishlar qo'shilgan!

**Comment by firdavsDev** [comment]
> @firdavsDev o'zgarishlarni pull qilib README.md dagilarni qayta run qilib ishlatib ko'ring. env filega o'zgarishlar qo'shilgan!

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/19d506ac-9353-42c9-a386-81c71b159b38">


MINIO_ACCESS_URL yo'q ekan

**Comment by bekzod818** [comment]
@firdavsDev localdagi .env da qolib ketibdi update qildim hozir

**Comment by firdavsDev** [comment]
> @firdavsDev localdagi .env da qolib ketibdi update qildim hozir

da bo'ldi o'rganib chiqdik.
